function kosilkav3(){var P='',wb='" for "gwt:onLoadErrorFn"',ub='" for "gwt:onPropertyErrorFn"',ib='"><\/script>',Z='#',Eb='&',ic='.cache.html',_='/',Xb='281F49FAC88FD49755B5E954BE7FB08B',Yb='2B51C0906B787B29845359AEB3A16D86',Zb='766A3FF776A1F0E44B79D63D43592560',$b='7F92D29A882DB0449E6F97D2091689A3',_b='8E460C69CD167633EA6A7A704267312F',ac='9ED8D390B0ABEF28F36192F69C434C60',hc=':',ob='::',qc='<script defer="defer">kosilkav3.onInjectionDone(\'kosilkav3\')<\/script>',hb='<script id="',rb='=',$='?',bc='ACBE896E2D01AF0D2E656A73EEC341FA',tb='Bad handler "',cc='C23EEE663D7FE9586997F18ECBFA2BFF',dc='C6EF795EC93EBA32AF3B899C8707E527',ec='DAE259DD873ED92F29975D709A47E5B4',pc='DOMContentLoaded',fc='EF13DD3ECA722463FBBECE869779B62A',gc='F8721F85F6B125EF4AD735871815BF52',jb='SCRIPT',Hb='Unexpected exception in locale detection, using default: ',Gb='_',Fb='__gwt_Locale',gb='__gwt_marker_kosilkav3',kb='base',cb='baseUrl',T='begin',S='bootstrap',bb='clear.cache.gif',qb='content',Cb='default',Y='end',Qb='gecko',Rb='gecko1_8',U='gwt.codesvr=',V='gwt.hosted=',W='gwt.hybrid',jc='gwt/standard/standard.css',vb='gwt:onLoadErrorFn',sb='gwt:onPropertyErrorFn',pb='gwt:property',oc='head',Ub='hosted.html?kosilkav3',nc='href',Pb='ie6',Ob='ie8',Nb='ie9',xb='iframe',ab='img',yb="javascript:''",Q='kosilkav3',eb='kosilkav3.nocache.js',nb='kosilkav3::',kc='link',Tb='loadExternalRefs',Bb='locale',Db='locale=',lb='meta',Ab='moduleRequested',X='moduleStartup',Mb='msie',mb='name',Jb='opera',zb='position:absolute;width:0;height:0;border:none',lc='rel',Lb='safari',db='script',Vb='selectingPermutation',Wb='sk',R='startup',mc='stylesheet',fb='undefined',Sb='unknown',Ib='user.agent',Kb='webkit';var l=window,m=document,n=l.__gwtStatsEvent?function(a){return l.__gwtStatsEvent(a)}:null,o=l.__gwtStatsSessionId?l.__gwtStatsSessionId:null,p,q,r,s=P,t={},u=[],v=[],w=[],x=0,y,z;n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:T});if(!l.__gwt_stylesLoaded){l.__gwt_stylesLoaded={}}if(!l.__gwt_scriptsLoaded){l.__gwt_scriptsLoaded={}}function A(){var b=false;try{var c=l.location.search;return (c.indexOf(U)!=-1||(c.indexOf(V)!=-1||l.external&&l.external.gwtOnLoad))&&c.indexOf(W)==-1}catch(a){}A=function(){return b};return b}
function B(){if(p&&q){var b=m.getElementById(Q);var c=b.contentWindow;if(A()){c.__gwt_getProperty=function(a){return H(a)}}kosilkav3=null;c.gwtOnLoad(y,Q,s,x);n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:X,millis:(new Date).getTime(),type:Y})}}
function C(){function e(a){var b=a.lastIndexOf(Z);if(b==-1){b=a.length}var c=a.indexOf($);if(c==-1){c=a.length}var d=a.lastIndexOf(_,Math.min(c,b));return d>=0?a.substring(0,d+1):P}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=m.createElement(ab);b.src=a+bb;a=e(b.src)}return a}
function g(){var a=F(cb);if(a!=null){return a}return P}
function h(){var a=m.getElementsByTagName(db);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(eb)!=-1){return e(a[b].src)}}return P}
function i(){var a;if(typeof isBodyLoaded==fb||!isBodyLoaded()){var b=gb;var c;m.write(hb+b+ib);c=m.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=jb){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return P}
function j(){var a=m.getElementsByTagName(kb);if(a.length>0){return a[a.length-1].href}return P}
var k=g();if(k==P){k=h()}if(k==P){k=i()}if(k==P){k=j()}if(k==P){k=e(m.location.href)}k=f(k);s=k;return k}
function D(){var b=document.getElementsByTagName(lb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(mb),g;if(f){f=f.replace(nb,P);if(f.indexOf(ob)>=0){continue}if(f==pb){g=e.getAttribute(qb);if(g){var h,i=g.indexOf(rb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=P}t[f]=h}}else if(f==sb){g=e.getAttribute(qb);if(g){try{z=eval(g)}catch(a){alert(tb+g+ub)}}}else if(f==vb){g=e.getAttribute(qb);if(g){try{y=eval(g)}catch(a){alert(tb+g+wb)}}}}}}
function E(a,b){return b in u[a]}
function F(a){var b=t[a];return b==null?null:b}
function G(a,b){var c=w;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
function H(a){var b=v[a](),c=u[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(z){z(a,d,b)}throw null}
var I;function J(){if(!I){I=true;var a=m.createElement(xb);a.src=yb;a.id=Q;a.style.cssText=zb;a.tabIndex=-1;m.body.appendChild(a);n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:X,millis:(new Date).getTime(),type:Ab});a.contentWindow.location.replace(s+L)}}
v[Bb]=function(){var b=null;var c=Cb;try{if(!b){var d=location.search;var e=d.indexOf(Db);if(e>=0){var f=d.substring(e+7);var g=d.indexOf(Eb,e);if(g<0){g=d.length}b=d.substring(e+7,g)}}if(!b){b=F(Bb)}if(!b){b=l[Fb]}if(b){c=b}while(b&&!E(Bb,b)){var h=b.lastIndexOf(Gb);if(h<0){b=null;break}b=b.substring(0,h)}}catch(a){alert(Hb+a)}l[Fb]=c;return b||Cb};u[Bb]={'default':0,sk:1};v[Ib]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(Jb)!=-1}())return Jb;if(function(){return b.indexOf(Kb)!=-1}())return Lb;if(function(){return b.indexOf(Mb)!=-1&&m.documentMode>=9}())return Nb;if(function(){return b.indexOf(Mb)!=-1&&m.documentMode>=8}())return Ob;if(function(){var a=/msie ([0-9]+)\.([0-9]+)/.exec(b);if(a&&a.length==3)return c(a)>=6000}())return Pb;if(function(){return b.indexOf(Qb)!=-1}())return Rb;return Sb};u[Ib]={gecko1_8:0,ie6:1,ie8:2,ie9:3,opera:4,safari:5};kosilkav3.onScriptLoad=function(){if(I){q=true;B()}};kosilkav3.onInjectionDone=function(){p=true;n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:Tb,millis:(new Date).getTime(),type:Y});B()};D();C();var K;var L;if(A()){if(l.external&&(l.external.initModule&&l.external.initModule(Q))){l.location.reload();return}L=Ub;K=P}n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:Vb});if(!A()){try{G([Wb,Jb],Xb);G([Wb,Pb],Yb);G([Cb,Ob],Zb);G([Cb,Nb],$b);G([Cb,Lb],_b);G([Wb,Ob],ac);G([Wb,Lb],bc);G([Wb,Rb],cc);G([Cb,Jb],dc);G([Cb,Pb],ec);G([Wb,Nb],fc);G([Cb,Rb],gc);K=w[H(Bb)][H(Ib)];var M=K.indexOf(hc);if(M!=-1){x=Number(K.substring(M+1));K=K.substring(0,M)}L=K+ic}catch(a){return}}var N;function O(){if(!r){r=true;if(!__gwt_stylesLoaded[jc]){var a=m.createElement(kc);__gwt_stylesLoaded[jc]=a;a.setAttribute(lc,mc);a.setAttribute(nc,s+jc);m.getElementsByTagName(oc)[0].appendChild(a)}B();if(m.removeEventListener){m.removeEventListener(pc,O,false)}if(N){clearInterval(N)}}}
if(m.addEventListener){m.addEventListener(pc,function(){J();O()},false)}var N=setInterval(function(){if(/loaded|complete/.test(m.readyState)){J();O()}},50);n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:Y});n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:Tb,millis:(new Date).getTime(),type:T});m.write(qc)}
kosilkav3();